version: 2
jobs:
  test_net35: &test_net35_body
    docker:
      - image: mono:latest
    working_directory: ~/workspace-net35
    steps:
      - checkout
      - run: nuget install NUnit.Console -ExcludeVersion -OutputDirectory .nuget
      - run: msbuild VJson.standalone/VJson.Editor.Tests/VJson.Editor.Tests.csproj /t:restore
      - run: msbuild VJson.standalone/VJson.Editor.Tests/VJson.Editor.Tests.csproj
      - run: mono --debug .nuget/NUnit.ConsoleRunner/tools/nunit3-console.exe VJson.standalone/VJson.Editor.Tests/bin/Debug/net35/VJson.Editor.Tests.dll

workflows:
  version: 2
  commit:
    jobs:
      - test_net35
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test_net35
#      - test_net45:
#      - test_netcoreapp2_0:
