version: 2

references:
  unity2018_3_docker_image: &unity2018_3_docker_image
    docker:
      - image: gableroux/unity3d:2018.3.12f1

  setup_unity_license_file: &setup_unity_license_file
    run:
      command: |
        mkdir -p /root/.cache/unity3d
        mkdir -p /root/.local/share/unity3d/Unity/
        echo $UNITY_ULF | base64 -d > /root/.local/share/unity3d/Unity/Unity_lic.ulf

jobs:
  test_net35:
    docker:
      - image: mono:latest
    working_directory: ~/workspace-net35
    steps:
      - checkout
      - run: apt-get update -yy && apt-get install -yy make git python3
      - run: make setup-net
      - run: make test-net35
      - store_test_results:
          path: test-results

  test_net45:
    docker:
      - image: mono:latest
    working_directory: ~/workspace-net45
    steps:
      - checkout
      - run: apt-get update -yy && apt-get install -yy make git python3
      - run: make setup-net
      - run: make test-net45
      - store_test_results:
          path: test-results

  test_netcoreapp2_0:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2.204
    working_directory: ~/workspace-netcoreapp2_0
    steps:
      - checkout
      - run: apt-get update -yy && apt-get install -yy make git python3
      - run: make setup
      - run: make test-netcore20
      - store_test_results:
          path: test-results

  coverage:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2.204
    working_directory: ~/workspace-netcoreapp2_0
    steps:
      - checkout
      - run: curl -s https://codecov.io/bash > codecov
      - run: chmod +x codecov
      - run: mkdir coverage
      - run: apt-get update -yy && apt-get install -yy make git python3
      - run: dotnet add StandaloneProject/Tests/Tests.csproj package coverlet.msbuild
      - run: make setup
      - run: make coverage-netcore20
      - run: ./codecov -f coverage/lcov.info

  test_unity2018_3:
    <<: *unity2018_3_docker_image
    working_directory: ~/workspace-unity2018.3.12f1
    steps:
      - run: apt-get update && apt-get install -y git zip && git --version
      - checkout
      - *setup_unity_license_file
      - run: make setup
      - run: ./ci/run-unity-editor-tests.sh
      - store_test_results:
          path: test-results

workflows:
  version: 2

  commit:
    jobs:
      - test_net35
      - test_net45
      - test_netcoreapp2_0
      - coverage:
          requires:
            - test_netcoreapp2_0
      - test_unity2018_3:
          requires:
            - test_net35
            - test_net45
            - test_netcoreapp2_0

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test_net35
      - test_net45
      - test_netcoreapp2_0
