//
// Copyright (c) 2019- yutopp (yutopp@gmail.com)
//
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at  https://www.boost.org/LICENSE_1_0.txt)
//

// THIS FILE IS AUTOMATICALLY GENERATED from TypeHelper.g.template.cs

using System;
using System.Collections.Generic;

namespace VJson
{
    static partial class TypeHelper
    {
$body
        public delegate bool Converter(object input, out object output);

        public static bool GetConverter(Type fromTy, Type toTy, out Converter converter)
        {
            Dictionary<Type, Converter> conv;
            if (!_convTable.TryGetValue(fromTy, out conv))
            {
                converter = null;
                return false;
            }

            return conv.TryGetValue(toTy, out converter);
        }
    }
}
