name: ci

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test_net35:
    runs-on: ubuntu-20.04
    container: mono:latest
    env:
      HAS_XSLTPROC: 1 # To export JUnit formatted Test Summary
    steps:
      - name: setup env
        run: apt-get update -yy && apt-get install -yy make git python3 xsltproc

      - uses: actions/checkout@v2

      - run: make setup-net

      - run: make test-net35

  test_net45:
    runs-on: ubuntu-20.04
    container: mono:latest
    env:
      HAS_XSLTPROC: 1 # To export JUnit formatted Test Summary
    steps:
      - name: setup env
        run: apt-get update -yy && apt-get install -yy make git python3 xsltproc

      - uses: actions/checkout@v2

      - run: make setup-net

      - run: make test-net45

  test_netcoreapp2_0:
    runs-on: ubuntu-20.04
    container: mcr.microsoft.com/dotnet/sdk:2.1-focal
    env:
      HAS_XSLTPROC: 1 # To export JUnit formatted Test Summary
    steps:
      - name: setup env
        run: apt-get update -yy && apt-get install -yy make git python3 xsltproc

      - uses: actions/checkout@v2

      - run: make setup

      - run: make test-netcore20

  coverage:
    needs: [test_netcoreapp2_0]
    runs-on: ubuntu-20.04
    container: mcr.microsoft.com/dotnet/sdk:2.1-focal
    env:
      HAS_XSLTPROC: 1 # To export JUnit formatted Test Summary
    steps:
      - name: setup env
        run: apt-get update -yy && apt-get install -yy make git python3 xsltproc

      - uses: actions/checkout@v2

      - run: |
          curl -s https://codecov.io/bash > codecov
          chmod +x codecov

      - run: make setup

      - run: mkdir coverage
      - run: make coverage-netcore20

      - run: ./codecov -f coverage/lcov.info

  test_unity:
    strategy:
      matrix:
        include:
          - unity_version: 2018.3.12f1
            docker_container: unityci/editor:ubuntu-2018.3.12f1-base-0.11.0
            ulf_secrets_key: UNITY_2018_3_ULF

    runs-on: ubuntu-20.04
    container: ${{ matrix.docker_container }}
    env:
      HAS_XSLTPROC: 1 # To export JUnit formatted Test Summary
    steps:
      - name: setup env
        run: |
          apt install -yy --no-install-recommends software-properties-common
          add-apt-repository -yy ppa:git-core/ppa
          apt update -yy
          apt install -yy --no-install-recommends make git python3 xsltproc
        env:
          DEBIAN_FRONTEND: noninteractive

      - run: /usr/bin/unity-editor -quit -batchmode -createManualActivationFile || true
        if: ${{ env.UNITY_ULF }} == ''
        env:
          UNITY_ULF: ${{ secrets[matrix.ulf_secrets_key] }}

      - uses: actions/upload-artifact@v1
        with:
          name: Unity_v${{ matrix.unity_version }}.alf
          path: ./Unity_v${{ matrix.unity_version }}.alf
        if: ${{ env.UNITY_ULF }} == ''
        env:
          UNITY_ULF: ${{ secrets[matrix.ulf_secrets_key] }}

      - run: echo "Secret key '$SECRETS_KEY' is empty" && exit 1
        if: ${{ env.UNITY_ULF }} == ''
        env:
          SECRETS_KEY: ${{ matrix.ulf_secrets_key }}
          UNITY_ULF: ${{ secrets[matrix.ulf_secrets_key] }}

      - name: setup unity license
        run: |
          mkdir -p ~/.cache/unity3d
          mkdir -p ~/.local/share/unity3d/Unity/
          echo "$UNITY_ULF" | base64 -d > ~/.local/share/unity3d/Unity/Unity_lic.ulf
        env:
          UNITY_ULF: ${{ secrets[matrix.ulf_secrets_key] }}

      - uses: actions/checkout@v2

      - run: make setup

      - run: ./ci/run-unity-editor-tests.sh
