name: ci

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test_net35:
    runs-on: ubuntu-20.04
    container: mono:latest
    env:
      HAS_XSLTPROC: 1 # To export JUnit formatted Test Summary
    steps:
      - name: setup env
        run: apt-get update -yy && apt-get install -yy make git python3 xsltproc

      - uses: actions/checkout@v2

      - run: make setup-net

      - run: make test-net35

  test_net45:
    runs-on: ubuntu-20.04
    container: mono:latest
    env:
      HAS_XSLTPROC: 1 # To export JUnit formatted Test Summary
    steps:
      - name: setup env
        run: apt-get update -yy && apt-get install -yy make git python3 xsltproc

      - uses: actions/checkout@v2

      - run: make setup-net

      - run: make test-net45

  test_netcoreapp2_0:
    runs-on: ubuntu-20.04
    container: mcr.microsoft.com/dotnet/sdk:2.1-focal
    env:
      HAS_XSLTPROC: 1 # To export JUnit formatted Test Summary
    steps:
      - name: setup env
        run: apt-get update -yy && apt-get install -yy make git python3 xsltproc

      - uses: actions/checkout@v2

      - run: make setup

      - run: make test-netcore20

  coverage:
    needs: [test_netcoreapp2_0]
    runs-on: ubuntu-20.04
    container: mcr.microsoft.com/dotnet/sdk:2.1-focal
    env:
      HAS_XSLTPROC: 1 # To export JUnit formatted Test Summary
    steps:
      - name: setup env
        run: apt-get update -yy && apt-get install -yy make git python3 xsltproc

      - uses: actions/checkout@v2

      - run: |
          curl -s https://codecov.io/bash > codecov
          chmod +x codecov

      - run: make setup

      - run: mkdir coverage
      - run: make coverage-netcore20
        
      - run: ./codecov -f coverage/lcov.info
